# Generated by Django 4.0.5 on 2022-06-22 06:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vish_app', '0003_contactpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
